# Config for single device LoRA DPO alignment in lora_dpo_single_device.py
# using a Llama2 7B model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-2-7b-hf --output-dir /tmp/Llama-2-7b-hf --ignore-patterns "*.bin" --hf-token <HF_TOKEN>
#
# To launch on a single device, run the following command from root:
#   tune run lora_dpo_single_device --config llama2/7B_lora_dpo_single_device
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run lora_dpo_single_device --config llama2/7B_lora_dpo_single_device checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works only for training on single device.

output_dir: /tmp/torchtune/llama2_7B/lora_dpo_single_device # /tmp may be deleted by your system. Change it to your preference.

# Model Arguments
lora:
  _component_: torchtune.models.llama3_2.lora_llama3_2_3b
  lora_attn_modules: ['q_proj', 'v_proj', 'output_proj']
  apply_lora_to_mlp: True
  lora_rank: 8  # higher increases accuracy and memory
  lora_alpha: 16  # usually alpha=2*rank
  lora_dropout: 0.0

model:
  _component_: model.Qwen3Model
  cfg:
    vocab_size: 151936           # Vocabulary size
    context_length: 40960        # Context length that was used to train the model
    emb_dim: 1024                 # Embedding dimension
    n_heads: 16                   # Number of attention heads
    n_layers: 28                  # Number of layers
    hidden_dim: 3072              # Size of the intermediate dimension in FeedForward
    head_dim: 128                 # Size of the heads in GQA
    qk_norm: True                 # Whether to normalize queries and values in GQA
    n_kv_groups: 8                # Key-Value groups for grouped-query attention
    rope_base: 1000000.0        # The base in RoPE's "theta"
    dtype: bf16        # Lower-precision dtype to reduce memory usage
  weight_path: "/Users/john/Downloads/model.safetensors"

# Tokenizer
tokenizer:   # TODO: this is LLM-specific data preprocessing
  _component_: torchtune.models.qwen3.qwen3_tokenizer
  path: /Users/john/Downloads/vocab.json
  merges_file: /Users/john/Downloads/merges.txt
  special_tokens_path: /Users/john/Downloads/tokenizer.json
  max_seq_len: null

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Llama-2-7b-hf
  checkpoint_files: [
    model-00001-of-00002.safetensors,
    model-00002-of-00002.safetensors
  ]
  adapter_checkpoint: null
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA2
resume_from_checkpoint: False
save_adapter_weights_only: False

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.hh_rlhf_helpful_dataset
seed: null
shuffle: True
batch_size: 4

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  weight_decay: 0.05
  lr: 5e-4
lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torchtune.rlhf.loss.DPOLoss

# Training
epochs: 1
max_steps_per_epoch: 1000
gradient_accumulation_steps: 8  # Use to increase effective batch size
compile: False  # torch.compile the model + loss, True increases speed + decreases memory

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: True
log_level: INFO  # DEBUG, WARN, etc.

# Environment
device: mps
dtype: bf16

# Memory management
enable_activation_checkpointing: False  # True reduces memory
enable_activation_offloading: False  # True reduces memory
